grep -E ",1$" GCcontent.csv > GCcontent_chr1.csv
grep -E ",2$" GCcontent.csv > GCcontent_chr2.csv
grep -E ",3$" GCcontent.csv > GCcontent_chr3.csv
grep -E ",4$" GCcontent.csv > GCcontent_chr4.csv
grep -E ",5$" GCcontent.csv > GCcontent_chr5.csv
grep -E ",6$" GCcontent.csv > GCcontent_chr6.csv
grep -E ",7$" GCcontent.csv > GCcontent_chr7.csv
grep -E ",8$" GCcontent.csv > GCcontent_chr8.csv
grep -E ",9$" GCcontent.csv > GCcontent_chr9.csv
grep -E ",10$" GCcontent.csv > GCcontent_chr10.csv
grep -E ",11$" GCcontent.csv > GCcontent_chr11.csv
grep -E ",12$" GCcontent.csv > GCcontent_chr12.csv
grep -E ",13$" GCcontent.csv > GCcontent_chr13.csv
grep -E ",14$" GCcontent.csv > GCcontent_chr14.csv
grep -E ",15$" GCcontent.csv > GCcontent_chr15.csv
grep -E ",16$" GCcontent.csv > GCcontent_chr16.csv
grep -E ",17$" GCcontent.csv > GCcontent_chr17.csv
grep -E ",18$" GCcontent.csv > GCcontent_chr18.csv
grep -E ",19$" GCcontent.csv > GCcontent_chr19.csv
grep -E ",20$" GCcontent.csv > GCcontent_chr20.csv
grep -E ",21$" GCcontent.csv > GCcontent_chr21.csv
grep -E ",22$" GCcontent.csv > GCcontent_chr22.csv
grep -E ",X$" GCcontent.csv > GCcontent_chrX.csv
grep -E ",Y$" GCcontent.csv > GCcontent_chrY.csv
